
import {
  Sprout,
  Leaf,
  Wheat,
  Layers3,
  CloudSun,
  LayoutDashboard,
  Database,
  BarChart3,
  BrainCircuit,
  ChevronDown,
  ChevronRight,
  Search,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Menu,
  X,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  PlusCircle,
  Edit3,
  Trash2,
  CalendarDays,
  HelpCircle,
  DollarSign,
  MapPin,
  Droplets,
  Thermometer,
  Tractor,
  Camera,
  ScanSearch,
  ClipboardList, // Added ClipboardList
  Recycle, // Added Recycle
  FlaskConical, // Added FlaskConical
} from 'lucide-react';

export const Icons = {
  Logo: Sprout,
  Planting: Leaf,
  Harvesting: Wheat,
  Soil: Layers3,
  Weather: CloudSun,
  Dashboard: LayoutDashboard,
  DataManagement: Database,
  Analytics: BarChart3,
  AIExpert: BrainCircuit,
  ChevronDown,
  ChevronRight,
  Search,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Menu,
  X,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  PlusCircle,
  Edit3,
  Trash2,
  Calendar: CalendarDays,
  Help: HelpCircle,
  Dollar: DollarSign,
  Location: MapPin,
  Water: Droplets,
  Temperature: Thermometer,
  Tractor,
  Camera,
  ScanSearch,
  ClipboardList, // Export ClipboardList
  Recycle, // Export Recycle
  FlaskConical, // Export FlaskConical
};

export type IconName = keyof typeof Icons;
