
import {
  Sprout,
  Leaf,
  Wheat,
  Layers3,
  CloudSun,
  LayoutDashboard,
  Database,
  BarChart3,
  BrainCircuit,
  ChevronDown,
  ChevronRight,
  Search,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Menu,
  X,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  PlusCircle,
  Edit3,
  Trash2,
  CalendarDays,
  HelpCircle,
  DollarSign,
  MapPin,
  Droplets,
  Thermometer,
  Tractor,
  Camera,
  ScanSearch,
  ClipboardList,
  Recycle,
  FlaskConical,
  FileText, 
  UserCircle,
  Archive, 
  Package,
  CreditCard,
  Map,
  Beef,
  ActivitySquare,
  GitFork,
  ListChecks, 
  Scale,
  Bell,
  Users, 
  Mail, 
  Smartphone, 
  TrendingUp, 
} from 'lucide-react';

export const Icons = {
  Logo: Sprout,
  Planting: Leaf,
  Harvesting: Wheat,
  Soil: Layers3,
  Weather: CloudSun,
  Dashboard: LayoutDashboard,
  DataManagement: Database,
  Analytics: BarChart3,
  AIExpert: BrainCircuit,
  BrainCircuit: BrainCircuit, // Added direct mapping
  ChevronDown,
  ChevronRight,
  Search,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Menu,
  X,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  PlusCircle,
  Edit3,
  Trash2,
  Calendar: CalendarDays,
  Help: HelpCircle,
  Dollar: DollarSign,
  Location: MapPin, 
  Water: Droplets,
  Temperature: Thermometer,
  Tractor,
  Camera,
  ScanSearch,
  ClipboardList, 
  Recycle,
  FlaskConical,
  Reporting: FileText, 
  UserCircle,
  FertilizerLog: Archive,
  InputsInventory: Package,
  Expenses: CreditCard,
  Map,
  Livestock: Beef,
  HealthRecord: ActivitySquare,
  Breeding: GitFork,
  FeedLog: ListChecks, 
  WeightLog: Scale,
  Bell,
  Users, 
  Mail,  
  Smartphone, 
  TrendingUp, 
  ListChecksFeatures: ListChecks, 
};

export type IconName = keyof typeof Icons;
