
import {
  Sprout,
  Leaf,
  Wheat,
  Layers3,
  CloudSun,
  LayoutDashboard,
  Database,
  BarChart3,
  BrainCircuit,
  ChevronDown,
  ChevronRight,
  Search,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Menu,
  X,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  PlusCircle,
  Edit3,
  Trash2,
  CalendarDays,
  HelpCircle,
  DollarSign,
  MapPin,
  Droplets,
  Thermometer,
  Tractor,
  Camera,
  ScanSearch,
  ClipboardList,
  Recycle,
  FlaskConical,
  FileText, 
  UserCircle,
  Archive, 
  Package,
  CreditCard,
  Map,
  Beef,
  ActivitySquare,
  GitFork,
  ListChecks, // Keep for generic list checks, or Features
  Scale,
  Bell,
  Users, // Added for About Us
  Mail, // Added for Contact
  Smartphone, // Added for UI/UX example
  TrendingUp, // Added for UI/UX example
} from 'lucide-react';

export const Icons = {
  Logo: Sprout,
  Planting: Leaf,
  Harvesting: Wheat,
  Soil: Layers3,
  Weather: CloudSun,
  Dashboard: LayoutDashboard,
  DataManagement: Database,
  Analytics: BarChart3,
  AIExpert: BrainCircuit,
  ChevronDown,
  ChevronRight,
  Search,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Info,
  Menu,
  X,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  PlusCircle,
  Edit3,
  Trash2,
  Calendar: CalendarDays,
  Help: HelpCircle,
  Dollar: DollarSign,
  Location: MapPin, 
  Water: Droplets,
  Temperature: Thermometer,
  Tractor,
  Camera,
  ScanSearch,
  ClipboardList, // For Task Logs
  Recycle,
  FlaskConical,
  Reporting: FileText, 
  UserCircle,
  FertilizerLog: Archive,
  InputsInventory: Package,
  Expenses: CreditCard,
  Map,
  Livestock: Beef,
  HealthRecord: ActivitySquare,
  Breeding: GitFork,
  FeedLog: ListChecks, 
  WeightLog: Scale,
  Bell,
  Users, // For About Us page link
  Mail,  // For Contact page link
  Smartphone, // For Landing Page benefit card
  TrendingUp, // For Landing Page benefit card
  ListChecksFeatures: ListChecks, // Explicitly for Features page link if needed to differentiate
};

export type IconName = keyof typeof Icons;

    